baseURL = 'https://benallen.dev'
languageCode = 'en-us'

title = 'Ben Allen.dev'
copyright = "{year} benallen.dev"

[imaging]
  anchor = 'Smart'
  bgColor = '#ffffff'
  quality = 100
  resampleFilter = 'Lanczos'

[taxonomies]
  category = 'categories'
  tag = 'tags'
  language = 'languages'

[permalinks]
  posts = "posts/:year/:month/:slug"
  page = "/:slug"

[params]
  headers = [
    ["Cache-Control", "max-age=3600"]
  ]
  social.github = "https://github.com/benallen-dev"
  social.linkedin = "https://www.linkedin.com/in/ben-allen"
  social.twitter = "https://twitter.com/benallen_dev"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = true
    style = "gruvbox"
    tabWidth = 4
  [markup.goldmark.parser.attribute]
    block = true
    title = true
