baseURL = 'https://benallen.dev'
languageCode = 'en-us'

title = 'Ben Allen.dev'
copyright = "{year} benallen.dev"

[imaging]
  anchor = 'Smart'
  bgColor = '#ffffff'
  quality = 100
  resampleFilter = 'Lanczos'

[taxonomies]
  category = 'categories'
  tag = 'tags'
  language = 'languages'

[permalinks]
  posts = "posts/:year/:month/:slug/"
  page = "/:slug/"

[params]
  logo = "/link.png"
  social.github = "https://github.com/benallen-dev"
  social.linkedin = "https://www.linkedin.com/in/ben-allen"

[markup.goldmark.parser.attribute]
  block = true
  title = true
